config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :releases, only: %i[ index edit] do
    member do
      get :ripped
      get :rip_later
    end
  end

  post 'update_collection', to: 'releases#update_collection'
  get 'four_to_the_floor', to: 'releases#four_to_the_floor'

  root to: 'pages#home'

  get 'error', to: 'pages#error'
  get 'authenticate', to: 'discogs#authenticate'
  get 'callback', to: 'discogs#callback'
  get 'collection', to: 'discogs#collection'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid ms-2">
  <% if current_user %>
    <nav>
      <mark>
        <%= link_to releases_path do %>
          <button class="btn btn-white">
            <i class="fa-solid fa-record-vinyl"></i> Collection
          </button>
        <% end %>
      </mark>
      <div class="whitey"></div>
      <mark>
        <%= link_to releases_path(ripped: "true") do %>
          <button class="btn btn-white"><i class="fa-solid fa-file"></i> Numérisés
          </button>
        <% end %>
      </mark>
      <div class="whitey"></div>
      <mark>
        <%= link_to releases_path(rip_later?: "true") do %>
          <button class="btn btn-white"><i class="fa-solid fa-clock"></i> To Rip
          </button>
        <% end %>
      </mark>
      <div class="whitey"></div>
      <mark>
        <button class="btn btn-white" data-action="click->update-collection#update" data-update-collection-target="button" data-id="<%= current_user.id %>">
          <i class="fa-solid fa-rotate"></i> Resynchroniser
        </button>
        </mark>
      <div class="whitey"></div>
      <mark>
        <button class="btn btn-white">
        <%= link_to four_to_the_floor_path do %>
          <i class="fa-solid fa-dice"></i> Four To The Floor
        <% end %>
        </button>
      </mark>

    </nav>
  <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6atYFWGfiNzgP_kcaamT8tY-Ii4JsX0P9OX9dZ4Jc5g&s", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>